# 1, Creating a tensor

In [2]:
import numpy as np
import tensorly as tl

In [4]:
Data = np.arange(24).reshape((3,4,2))
Data

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

reshape((3,4,2))函数是创造出一个3位数组，第一维度有3个元素，每个元素都是4\*2的矩阵

In [5]:
type(Data)

numpy.ndarray

In [6]:
# Transfer Data as tensor by using tensorly's function: tensor()
X = tl.tensor(Data)
X


[[[  0.   1.]
  [  2.   3.]
  [  4.   5.]
  [  6.   7.]]

 [[  8.   9.]
  [ 10.  11.]
  [ 12.  13.]
  [ 14.  15.]]

 [[ 16.  17.]
  [ 18.  19.]
  [ 20.  21.]
  [ 22.  23.]]]
<NDArray 3x4x2 @cpu(0)>

tensor()把numpy.ndarray转变成**mxnet.ndarray.ndarray.NDArray**

In [7]:
type(X)

mxnet.ndarray.ndarray.NDArray

张量的索引(Index)

In [8]:
X[:,:,0]


[[  0.   2.   4.   6.]
 [  8.  10.  12.  14.]
 [ 16.  18.  20.  22.]]
<NDArray 3x4 @cpu(0)>

In [9]:
X[0,:,:]


[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]]
<NDArray 4x2 @cpu(0)>

In [10]:
X[0,0,0]


[ 0.]
<NDArray 1 @cpu(0)>

In [11]:
X[0,0,:]


[ 0.  1.]
<NDArray 2 @cpu(0)>

# 2, Setting the backend   选择数据框架基础

在**tensorly**中可以选择替换**mxnet**或者**Numpy**作为**Backend**作为数据框架基础进行操作！

默认情况下，以**mxnet**作为数据框架基础。


In [12]:
# 进行的backend的切换
tl.set_backend('numpy')
# 仍然有问题，先搁置，之后解决？？！！！！

AttributeError: 'module' object has no attribute 'reload'

In [13]:
type(X)

mxnet.ndarray.ndarray.NDArray

# 3,Basic Tensor Operations

## 3.1 Unfolding （展开）aslo called *Matrization(矩阵化)*

