# Markdown语法

网址如下：

https://laravel-china.org/topics/621/you-will-be-able-to-master-these-markdown-grammars

# 1，数组和标量之间的运算_Notes

1.1 不需要编写循环即可对数据执行批量运算,
**矢量化(Vectorization)**,
大小相等的数组之间的任何算术运算都会讲运算应用到元素级,
不同大小的数组之间的运算叫做**广播(broadcasting)**

In [1]:
#常用的引用
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [3]:
arr+arr

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [4]:
arr*arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

# 2，基本的索引和切片 

和Python基本的索引和切片操作基本一致

In [5]:
Arr = np.arange(10)
Arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

索引操作, 从0开始

In [6]:
Arr[5]

5

**切片操作,arr[n.m]，从arr[n]开始到arr[m-1]结束！**

In [7]:
Arr[5:8]

array([5, 6, 7])

切片操作并赋值，切片内的元素全部被赋予同一值,多维数组的情况下，所有最底层的元素也都会被赋予相同的值

In [8]:
Arr[5:8] = 12
Arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

**跟列表最重要的区别在于，数组切片是原始数组的视图，这意味着数组不会被复制，在视图上的任何修改都会直接反映到原数组上,主要是因为NumPy主要是为了处理大数据，如果在操作是进行复制，会占用大量内存和花费很长时间，影响处理效率！！！**

In [9]:
arr_slice = Arr[1:3]
arr_slice[1] = 12345
Arr

array([    0,     1, 12345,     3,     4,    12,    12,    12,     8,     9])

多数数组中，索引和切片有更多的用途，更实用！

In [10]:
arr2D = np.arange(9).reshape((3,3))
arr2D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

2维数组的单个索引为一个数组，双索引为一个元素，更高维度依次类推！

In [11]:
arr2D[1]

array([3, 4, 5])

In [12]:
arr2D[1][2]

5

In [13]:
arr2D[1,2] #另一种多维数组索引的方式

5

# 3，切片索引

ndarray切片语法和Python列表这样的一维对象差不多

In [14]:
simpledata = [0,1,2,3,4,64,64,64,8,9]
ARR = np.array(simpledata)
ARR[3:6]

array([ 3,  4, 64])

高纬度对象花样更多，可以在一个或多个轴上进行切片，也可以跟整数索引混合使用

二维数组实例(每单个索引为一个数组)，三维数组，高维数组的情况则依次类推.........


In [15]:
arr2D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
arr2D[1:2]

array([[3, 4, 5]])

切片是沿着一个轴向选取元素的，我们可以一次传入多个切片，就像传入多个索引一样

In [17]:
arr2D[:2,1:]

array([[1, 2],
       [4, 5]])

**合理灵活的利用索引可以灵活的对高维数组进行切片处理！！！**

# 4，布尔型索引

In [18]:
# 创建一个存储姓名的数组（含有重复项）
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
# 创建一个随机的数组，利用NumPy.random的randn()函数生成一些正态分布的随机函数
RandomData = np.random.randn(7,4)
RandomData

array([[-0.73338338, -1.43856419, -1.01098248,  0.98184859],
       [-0.65929253, -1.61393238,  0.85454267,  0.73356235],
       [ 0.15153255, -0.13243499, -0.03494967, -0.56956098],
       [-0.66356114, -0.10453413, -0.38441812,  0.53231678],
       [ 0.65892474, -0.15610868, -1.12717645,  1.08511463],
       [-0.84044719, -0.53929449,  1.75230622,  0.81533072],
       [-0.785127  , -1.10300697, -0.0431978 ,  0.10224708]])

假设每个名字都对应data数组中的一行，希望选出对应于名字“Bob”的所有行，执行比较运算“==”，可以得到一个布尔型数组,**其他比较运算符或逻辑运算符也可以**

In [19]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

这个布尔型数组可以用于数组索引，**但是布尔型数组的长度必须跟被索引的轴长度一致**

In [20]:
BoolArr = names =='Bob'
RandomData[BoolArr] # 索引，选取names中未True时所对应的索引(切片)

array([[-0.73338338, -1.43856419, -1.01098248,  0.98184859],
       [-0.66356114, -0.10453413, -0.38441812,  0.53231678]])

也可以将布尔型数组和切片，整数（或整数序列）混合使用

In [21]:
RandomData[BoolArr,2:] # 配切片索引

array([[-1.01098248,  0.98184859],
       [-0.38441812,  0.53231678]])

In [22]:
RandomData[BoolArr,2] # 配单个索引

array([-1.01098248, -0.38441812])

**??通过布尔型索引选取数组中的数据，将总是创建数据的副本，即返回一模一样的数组,**

通过布尔型数组设置值是非常灵活实用的手段


In [23]:
# 将数组中所有的负值设置为0值
RandomData[RandomData < 0] = 0 
RandomData

array([[ 0.        ,  0.        ,  0.        ,  0.98184859],
       [ 0.        ,  0.        ,  0.85454267,  0.73356235],
       [ 0.15153255,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.53231678],
       [ 0.65892474,  0.        ,  0.        ,  1.08511463],
       [ 0.        ,  0.        ,  1.75230622,  0.81533072],
       [ 0.        ,  0.        ,  0.        ,  0.10224708]])

# 5，花式索引(Fancy indexing)

NumPy术语，它值得是利用整数数组进行索引

In [24]:
# 创建一个8*4的数组
FanArr = np.empty((8,4))
for i in range(8):
    FanArr[i] = i
FanArr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

为了以特定的顺序选取子集，只需传入一个用于指定顺序的整数列表或ndarray即可：

In [25]:
FanArr[[4,3,0,6]]
# 即选取第4+1,3+1,0+1,6+1行

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [26]:
# 使用负数索引将会从末尾开始选取行：
FanArr[[-3,-5,-7]]
# 即选择倒数第3,5,7行

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

一次传入多个索引数组有个特点：它返回一个一维数组，其中的元素对应各个索引元组：

In [28]:
FanArr2 = np.arange(32).reshape((8,4))
FanArr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [29]:
FanArr2[[1,5,7,2],[0,3,1,2]]
# 最终选出的元素是（1.0），（5,3），（7,1），（2,2）

array([ 4, 23, 29, 10])

In [31]:
FanArr2[[1,5,7,2]][:,[0,3,1,2]]
# 选出[1,5,7,2]指定的行，并按照[0,3,1,2]的顺序进行排序....

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

可以使用np.ix_()函数，它可以将两个以为整数数组转换成一个用于选取方形区域的索引器

In [38]:
index = np.ix_([1,5,7,2],[0,3,1,2])
index

(array([[1],
        [5],
        [7],
        [2]]), array([[0, 3, 1, 2]]))

In [40]:
FanArr2[index]
# 与FanArr2[[1,5,7,2]][:,[0,3,1,2]] 有共同的效果

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

**花式索引跟切片不一样，它总是将数据复制到新数组中**