In [1]:
#常用的引用
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

# 1, np.where()函数

**numpy.where()**函数是三元表达式" x if condition else y "的矢量化版本，常用于根据一个数组，创造另一个数组

In [2]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])
# 根据cond中的值选取xarr和yarr的值，cond为True的时候，选取xarr的值，否则选取yarr的值
# 一般做法：
result = [(x if c else y)
          for x,y,c in zip(xarr,yarr,cond)]
# 缺点很多： 不适合大数组处理，速度慢
#           无法用于多维数组
# 使用np.where(c,x,y)函数的话则非常好用简单  " x if c else y" 即"c"为真则"x",否则"y"
# x,y 不必是数组，也可以标量
Result = np.where(cond,xarr,yarr)
Result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

举例Example One

In [3]:
# 举例
# 一个由随机数据生成的矩阵，
arr = np.random.randn(4,4)
arr

array([[ 0.77147165, -0.03649803,  0.88275289, -1.0731329 ],
       [-0.70163564, -0.56031334, -1.08799471, -0.74808535],
       [-0.98770586,  0.53370283, -0.13926258,  0.63087443],
       [ 0.38596139,  0.19575184, -1.38525303, -1.22402464]])

In [4]:
# 希望将所有的正值替换为2，复制替换为-2
np.where(arr>0,2,-2)

array([[ 2, -2,  2, -2],
       [-2, -2, -2, -2],
       [-2,  2, -2,  2],
       [ 2,  2, -2, -2]])

In [5]:
# 正值为2，其余不变
np.where(arr>0,2,arr)

array([[ 2.        , -0.03649803,  2.        , -1.0731329 ],
       [-0.70163564, -0.56031334, -1.08799471, -0.74808535],
       [-0.98770586,  2.        , -0.13926258,  2.        ],
       [ 2.        ,  2.        , -1.38525303, -1.22402464]])

**np.where()函数可以嵌套使用**



# 2，数学和统计方法


聚合计算（Aggregation或叫作约简（Reduction））, 常用函数：sum(),mean(), 标准差std()

In [6]:
ARR = np.random.randn(5,4) # 正态分布的数据
ARR

array([[-1.29970553,  1.0127446 , -1.56677274,  0.00726409],
       [-0.29593664, -0.41942201, -0.44370151,  0.5809497 ],
       [ 1.64887781, -0.56571302,  1.07023471,  1.5462836 ],
       [-0.38132988,  0.37577736, -0.66345389,  1.40155691],
       [-1.96854291, -2.02040046,  1.90055802,  0.94413698]])

In [7]:
# mean()函数，平均值
np.mean(ARR)
ARR.mean()
# 两种调用方式都可以使用，效果相同
# sum（）函数，求和
ARR.sum()

0.86340519450439079

mean(),sum()这类函数可以接受一个axis参数（用于计算该轴向上的统计值），**最终结果是一个少一维的数组**

In [8]:
# axis = 1 时的数据取平均值,即对每一行的数据进行平均值计算，只保留计算之后的平均值
# axis = 0 时，数据的求和，即对每一列数据求和，只保留计算之后的总和值
# 这种情况相当于压缩原始数据的一个维度
ARR.mean(axis=1)
ARR.sum(0)

array([-2.29663715, -1.61701352,  0.2968646 ,  4.48019127])

**其他如cumsum和cumprod之类的方法则不聚合，而是产生一个由中间结果组成的数组**

## 2.1 基本数组统计方法

<img src="https://github.com/ColinsGitCode/All_Files/blob/master/LearnCode/Python/JupyterNotebook/ipynbFiles/Materials/statistical_func.jpg?raw=true" />

# 3，用于布尔型数组的方法

在此类方法的处理中，布尔类型会变为1和0两种数值

In [9]:
BARR = np.random.randn(100)
(BARR > 0).sum() #正值的数量

54

In [10]:
Bools = np.array([False,False,True,False])
# 测试数组中是否存在一个或多个True
Bools.any()

True

In [11]:
# 测试数组中是否全是True
Bools.all()

False