In [10]:
#常用的引用
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

# 1, np.where()函数

**numpy.where()**函数是三元表达式" x if condition else y "的矢量化版本，常用于根据一个数组，创造另一个数组

In [11]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])
# 根据cond中的值选取xarr和yarr的值，cond为True的时候，选取xarr的值，否则选取yarr的值
# 一般做法：
result = [(x if c else y)
          for x,y,c in zip(xarr,yarr,cond)]
# 缺点很多： 不适合大数组处理，速度慢
#           无法用于多维数组
# 使用np.where(c,x,y)函数的话则非常好用简单  " x if c else y" 即"c"为真则"x",否则"y"
# x,y 不必是数组，也可以标量
Result = np.where(cond,xarr,yarr)
Result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

举例Example One

In [12]:
# 举例
# 一个由随机数据生成的矩阵，
arr = np.random.randn(4,4)
arr

array([[-0.25631224, -0.86075433,  0.38955038, -1.71785285],
       [ 1.08070808, -0.19223254, -1.95410074,  0.26731989],
       [ 2.8246686 ,  1.16649623,  0.16024787,  1.43858356],
       [ 1.94554507,  0.22142518,  0.23059236,  0.20841096]])

In [13]:
# 希望将所有的正值替换为2，复制替换为-2
np.where(arr>0,2,-2)

array([[-2, -2,  2, -2],
       [ 2, -2, -2,  2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2]])

In [14]:
# 正值为2，其余不变
np.where(arr>0,2,arr)

array([[-0.25631224, -0.86075433,  2.        , -1.71785285],
       [ 2.        , -0.19223254, -1.95410074,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ]])

**np.where()函数可以嵌套使用**



# 2，数学和统计方法


聚合计算（Aggregation或叫作约简（Reduction））, 常用函数：sum(),mean(), 标准差std()

In [16]:
ARR = np.random.randn(5,4) # 正态分布的数据
ARR

array([[ 0.65288867,  0.27590398,  0.77033146, -0.48917191],
       [ 0.06950676,  0.49770416,  0.60947379, -1.12128145],
       [ 0.1553672 ,  1.4078704 ,  0.02298838,  1.25793441],
       [ 0.62339524, -0.05488941,  0.50143082, -0.41957068],
       [ 0.07441432, -0.29071062,  0.45448606, -1.20831397]])

In [18]:
# mean()函数，平均值
np.mean(ARR)
ARR.mean()
# 两种调用方式都可以使用，效果相同
# sum（）函数，求和
ARR.sum()

3.7897576008549358

mean(),sum()这类函数可以接受一个axis参数（用于计算该轴向上的统计值），**最终结果是一个少一维的数组**

In [23]:
# axis = 1 时的数据取平均值,即对每一行的数据进行平均值计算，只保留计算之后的平均值
# axis = 0 时，数据的求和，即对每一列数据求和，只保留计算之后的总和值
# 这种情况相当于压缩原始数据的一个维度
ARR.mean(axis=1)
ARR.sum(0)

array([ 1.57557219,  1.8358785 ,  2.35871051, -1.9804036 ])

**其他如cumsum和cumprod之类的方法则不聚合，而是产生一个由中间结果组成的数组**

## 2.1 基本数组统计方法

<img src="https://github.com/ColinsGitCode/All_Files/blob/master/LearnCode/Python/JupyterNotebook/ipynbFiles/Materials/statistical_func.jpg?raw=true" />

# 3，用于布尔型数组的方法

在此类方法的处理中，布尔类型会变为1和0两种数值

In [24]:
BARR = np.random.randn(100)
(BARR > 0).sum() #正值的数量

53

In [25]:
Bools = np.array([False,False,True,False])
# 测试数组中是否存在一个或多个True
Bools.any()

True

In [26]:
# 测试数组中是否全是True
Bools.all()

False