In [1]:
#常用的引用
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

# 1, 排序

可以利用sort()函数进行排序

In [2]:
arr = np.random.randn(8)
arr

array([-0.05938836,  0.50609981,  0.30755123, -0.03603856, -0.9275136 ,
       -1.10937861,  0.70461733,  1.78788401])

In [3]:
arr.sort()
arr

array([-1.10937861, -0.9275136 , -0.05938836, -0.03603856,  0.30755123,
        0.50609981,  0.70461733,  1.78788401])

多维数组可以只在某些轴上进行排序，只需将轴编号传给sort()函数即可

In [4]:
Arr = np.random.randn(5,3)
Arr

array([[ 0.36046911,  0.02217511, -1.00259012],
       [-0.05055334,  1.52645271,  0.73821394],
       [-1.24520153, -1.75917501,  1.09917348],
       [-0.35270758, -0.18861142, -0.9624833 ],
       [ 0.65476095, -0.31250764, -0.10221234]])

In [5]:
Arr.sort(1) # 只在axis = 1 的轴向上进行排序，即对每一行进行排序
Arr

array([[-1.00259012,  0.02217511,  0.36046911],
       [-0.05055334,  0.73821394,  1.52645271],
       [-1.75917501, -1.24520153,  1.09917348],
       [-0.9624833 , -0.35270758, -0.18861142],
       [-0.31250764, -0.10221234,  0.65476095]])

**顶级方法np.sort()返回的是数组的已排序副本，而就地排序则会修改数组本身**

**实例**

计算数组的分位数： 即先对数组进行排序，然后选取特定位置，程序实例如下

In [6]:
# 取得一个数组的 “5%分位数”
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))]

-1.6662154365890158

# 2，唯一化以及其他的集合逻辑

2.1 针对一维ndarray的基本集合运算

np.unique() 函数，用于找出数组中的唯一值并返回已排序的结果,**即唯一显示数组中存在的值，去除重复的项**


In [7]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
ints = np.array([3,3,3,2,2,1,1,4,4])
np.unique(names)

array(['Bob', 'Joe', 'Will'],
      dtype='<U4')

In [8]:
np.unique(ints)

array([1, 2, 3, 4])

np.in1d()用于测试一个数组中值在另一个数组中的成员资格，返回一个布尔型数组

In [9]:
values = np.array([6,0,0,3,2,5,6])
# 测试values中的值在数组【2,3,6】中是否存在
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True], dtype=bool)

**数组的集合运算**

<img src="https://github.com/ColinsGitCode/All_Files/blob/master/LearnCode/Python/JupyterNotebook/ipynbFiles/Materials/Array_Sets_Func.jpg?raw=true" />

