In [23]:
#常用的引用
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

# 1, 排序

可以利用sort()函数进行排序

In [24]:
arr = np.random.randn(8)
arr

array([ 0.35142853, -1.43437335, -1.03574898,  0.34687662,  0.21699826,
        1.63160334, -0.796124  ,  0.69017493])

In [25]:
arr.sort()
arr

array([-1.43437335, -1.03574898, -0.796124  ,  0.21699826,  0.34687662,
        0.35142853,  0.69017493,  1.63160334])

多维数组可以只在某些轴上进行排序，只需将轴编号传给sort()函数即可

In [ ]:
Arr = np.random.randn(5,3)
Arr

In [27]:
Arr.sort(1) # 只在axis = 1 的轴向上进行排序，即对每一行进行排序
Arr

array([[ 0.38791842,  0.66166821,  0.84130335],
       [-0.35022882,  0.65195474,  1.06620951],
       [-1.81888806,  0.34720527,  0.62226655],
       [-1.66511883, -0.54729964, -0.16489504],
       [-1.52415689, -0.22134102,  0.58597909]])

**顶级方法np.sort()返回的是数组的已排序副本，而就地排序则会修改数组本身**

**实例**

计算数组的分位数： 即先对数组进行排序，然后选取特定位置，程序实例如下

In [28]:
# 取得一个数组的 “5%分位数”
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))]

-1.5684623344642297

# 2，唯一化以及其他的集合逻辑

2.1 针对一维ndarray的基本集合运算

np.unique() 函数，用于找出数组中的唯一值并返回已排序的结果,**即唯一显示数组中存在的值，去除重复的项**


In [29]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
ints = np.array([3,3,3,2,2,1,1,4,4])
np.unique(names)

array(['Bob', 'Joe', 'Will'], 
      dtype='|S4')

In [30]:
np.unique(ints)

array([1, 2, 3, 4])

np.in1d()用于测试一个数组中值在另一个数组中的成员资格，返回一个布尔型数组

In [31]:
values = np.array([6,0,0,3,2,5,6])
# 测试values中的值在数组【2,3,6】中是否存在
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True], dtype=bool)

**数组的集合运算**

<img src="https://github.com/ColinsGitCode/All_Files/blob/master/LearnCode/Python/JupyterNotebook/ipynbFiles/Materials/Array_Sets_Func.jpg?raw=true" />

